---
title: "Red List Index of ecosystems assessments"
subtitle: "Summary Findings"

date: last-modified
date-format: DD-MM-YYYY
---

```{r setup}
#| echo: false
#| message: false
#| warning: false

#if (!requireNamespace(c("magrittr","dplyr", "ggplot2", "ggthemes"), quietly = TRUE)) {
#  install.packages(c("magrittr","dplyr", "ggplot2", "ggthemes"))
#}

#devtools::install_github("SANBI-NBA/nbaR", force = T)

library(nbaR)
library(dplyr)
library(tidyr)
#library(stringi)
library(rlang)
library(gt)
library(ggplot2)
library(RColorBrewer)
library(here)

```

```{r, echo=FALSE}

RLIe_GET_L2 <- readxl::read_xlsx("./data/RLIe_GET_L2.xlsx")
RLIe_GET_L3 <- readxl::read_xlsx("./data/RLIe_GET_L3.xlsx")
RLIe_national <- readxl::read_xlsx("./data/RLIe_national.xlsx")

GET_L2.count <- readxl::read_xlsx("./data/GET_L2.count.xlsx")
GET_L3.count <- readxl::read_xlsx("./data/GET_L3.count.xlsx")

GET_L2.ecosytems_count <- readxl::read_xlsx("./data/GET_L2.ecosytems_count.xlsx")
GET_L3.ecosytems_count <- readxl::read_xlsx("./data/GET_L3.ecosytems_count.xlsx")
```

## Global Ecosystem Typology at Level 2

```{r, echo=FALSE, fig.width=8, fig.height=4.5}
#| label: fig-1
#| fig-cap: "Red List Index of Ecosystems (RLIe) assessed at IUCN Global Ecosystem Typology (GET) Level 2 for South Africa. Changes in the slope of each line indicate the rate at which ecosystem functional groups within each GET Level 2 category are becoming more threatened over time. Lower RLIe values indicate movement towards ecosystem collapse (an RLIe value of 0 indicates complete ecosystem collapse). The aggregate line represents the national mean RLIe across all assessed GET Level 2 categories."

# ---- GET_L2 ----
getL2_levels <- unique(RLIe_GET_L2$GET)
getL2_colors <- setNames(brewer.pal(n = length(getL2_levels), name = "Paired"), getL2_levels)

GET_L2.plot <- ggplot() +
  
  geom_line(data = RLIe_GET_L2,
            aes(x = Year, y = RLIE, color = GET),
            size = 0.7) +
  
  geom_point(data = RLIe_GET_L2,
             aes(x = Year, y = RLIE, color = GET),
             size = 3) +
  
  # Aggregate (national)
  geom_line(data = RLIe_national,
            aes(x = Year, linetype = "Aggregate", shape = "Aggregate", y = RLIE),
            color = "black",
            size = 0.7) +
  
  geom_point(data = RLIe_national,
             aes(x = Year, y = RLIE, shape = "Aggregate"),
             color = "black",
             size = 3) +
  
  # Scales
  scale_color_manual(name = "IUCN Global Ecosystem Typology (Level 2)", values = getL2_colors) +
  scale_linetype_manual(name = "", values = c("Aggregate" = "dotted"), guide = guide_legend(order = 2)) +
  scale_shape_manual(name = "", values = c("Aggregate" = 20), guide = guide_legend(order = 2)) +
  scale_x_continuous(breaks = unique(RLIe_GET_L2$Year)) +
  scale_y_continuous(limits = c(0.4, 1), breaks = seq(0.5, 1, 0.1)) +
  
  # Labels
  labs(x = "Year", y = "Red List Index of ecosystems") +
  
  # Theme
  theme_classic() +
  theme(legend.position = "right",
        legend.box = "vertical",
        legend.text = element_text(size = 8.5),
        legend.title = element_text(size = 10, lineheight = 1.3, margin = margin(b = 7)),
        legend.spacing.y = unit(0.4, 'cm'),
        legend.key.size = unit(0.6, "cm"),
        axis.title.x = element_text(size = 10, margin = margin(t = 12)),
        axis.title.y = element_text(size = 10, margin = margin(r = 12)),
        axis.text = element_text(size = 8.5))

print(GET_L2.plot)

ggsave(filename = "GET_L2.plot.png",
       plot = GET_L2.plot,
       path = "./images",
       width = 45,
       height = 30,
       dpi = 300)
```

## Global Ecosystem Typology at Level 3

::: scrolling
```{r, echo=FALSE, fig.width=8.5, fig.height=4.5}
#| label: fig-2
#| fig-cap: "Red List Index of Ecosystems (RLIe) assessed at IUCN Global Ecosystem Typology (GET) Level 3 for South Africa. Changes in the slope of each line indicate the rate at which ecosystem functional groups within each GET Level 3 category are becoming more threatened over time. Lower RLIe values indicate movement towards ecosystem collapse (an RLIe value of 0 indicates complete ecosystem collapse). The aggregate line represents the national mean RLIe across all assessed GET Level 3 categories."
#| 
# ---- Color Palette ----
unique_GETs <- unique(RLIe_GET_L3$GET)
get_colors <- setNames(brewer.pal(n = length(unique_GETs), name = "Paired"),unique_GETs)

# ---- GET_L3 ----

GET_L3.plot <- ggplot() +
  
  geom_line(data = RLIe_GET_L3,
            aes(x = Year, y = RLIE, color = GET),
            size = 0.7) +
  
  geom_point(data = RLIe_GET_L3,
             aes(x = Year, y = RLIE, color = GET),
             size = 3) +
  
  # Aggregate (national)
  geom_line(data = RLIe_national,
            aes(x = Year, linetype = "Aggregate", shape = "Aggregate", y = RLIE),
            color = "black",
            size = 0.7) +
  
  geom_point(data = RLIe_national,
             aes(x = Year, y = RLIE, shape = "Aggregate"),
             color = "black",
             size = 3) +
  
  # Scales
  scale_color_manual(name = "IUCN Global Ecosystem Typology (Level 3)", values = get_colors) +
  scale_linetype_manual(name = "", values = c("Aggregate" = "dotted"), guide = guide_legend(order = 2)) +
  scale_shape_manual(name = "", values = c("Aggregate" = 20), guide = guide_legend(order = 2)) +
  scale_x_continuous(breaks = unique(RLIe_GET_L3$Year)) +
  scale_y_continuous(limits = c(0.4, 1), breaks = seq(0.5, 1, 0.1)) +
  
  # Labels
  labs(x = "Year", y = "Red List Index of ecosystems") +
  
  # Theme
  theme_classic() +
  theme(legend.position = "right",
        legend.box = "vertical",
        legend.text = element_text(size = 9),
        legend.title = element_text(size = 10, lineheight = 1.3, margin = margin(b = 7)),
        legend.spacing.y = unit(0.4, 'cm'),
        legend.key.size = unit(0.6, "cm"),
        axis.title.x = element_text(size = 10, margin = margin(t = 12)),
        axis.title.y = element_text(size = 10, margin = margin(r = 12)),
        axis.text = element_text(size = 8.5))

print(GET_L3.plot)

ggsave(filename = "GET_L3.plot.png",
       plot = GET_L3.plot,
       path = "./images",
       width = 45,
       height = 30,
       dpi = 300)
```
:::


##